# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IS590ADV - Advanced Data Viz
email: matthewturk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the course website for IS590ADV in Spring 2019
baseurl: "/spr2019-adv" # the subpath of your site, e.g. /blog
url: "https://uiuc-ischool-dataviz/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: uiuc-ischool-dataviz
branch: master

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#

defaults:
  -
    scope:
      path: "lecture*.md"
    values:
      layout: "lecture.html"
